### ISSUE TITLE
(Bug) No shield from Modded items

### ISSUE THREAD

**Issue by Coffe-e** [Horseyboi/RiskyRain2Mods#3]
Itemtweaks Prevents modded items such as Blood Soaked Shield from Aetherium, or Kinetic Engine from BORBO from giving any Maximum Shield to the player's health.

**Comment by Horseyboi** [comment]
I can't seem to replicate this issue with Aetherium. Are you sure ItemTweaks is causing it?
![image](https://user-images.githubusercontent.com/69808736/107295679-dab86900-6a3d-11eb-9c12-098c47d1e193.png)

**Comment by Coffe-e** [comment]
Odd. It's probably an incompatibility with BORBO specifically that does that then, since I had limited the mods to Itemtweaks, borbo, ror2api, and debugtoolkit
Oddly enough though, borbo doesn't cause this issue with aetherium, or any other item mod for that matter.

**Comment by Coffe-e** [comment]
I think I remember borbo itself having this issue with other modded items in the past too, but I'm not sure about that. 
Possibly talk to duck about the issue to see what he knows?

**Comment by Horseyboi** [comment]
Uploading a build today that should fix incompatibility issues with BORBO:
![image](https://user-images.githubusercontent.com/69808736/107854670-7bff4080-6deb-11eb-8108-70927623b863.png)
I have to fix the rest of my hooks but this should at least fix the conflict.
